"""
state/conversation_store.py
----------------------------
In-memory store for active Vera conversations.

Each Conversation tracks:
  - conversation_id      unique string (generated by the bot on first send)
  - merchant_id          which merchant this conversation is with
  - customer_id          populated only for customer-facing messages
  - trigger_id           the trigger that started this conversation
  - messages             list of all turns (both Vera and merchant/customer)
  - turn_number          current turn index
  - state                ConversationState enum
  - auto_reply_streak    consecutive identical/canned reply count (for auto-reply detection)
  - last_sent_bodies     list of message bodies the bot has sent (for repetition detection)
  - suppression_key      the trigger's suppression key (dedup across conversations)

State machine overview:
  NEW → PITCHING → QUALIFYING → COMMITTED → ACTIONING → WAITING → ENDED
  At any point: → AUTO_REPLY | NOT_INTERESTED

Thread safety: same rationale as context_store.py — single-threaded judge is
the normal case; a dict + threading.Lock is sufficient.
"""

from __future__ import annotations

import threading
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional


class ConversationState(str, Enum):
    NEW = "NEW"
    PITCHING = "PITCHING"
    QUALIFYING = "QUALIFYING"
    COMMITTED = "COMMITTED"
    ACTIONING = "ACTIONING"
    WAITING = "WAITING"
    AUTO_REPLY = "AUTO_REPLY"
    NOT_INTERESTED = "NOT_INTERESTED"
    ENDED = "ENDED"


@dataclass
class Message:
    """One turn in a conversation."""
    role: str                  # "vera" | "merchant" | "customer"
    body: str
    turn_number: int
    received_at: Optional[str] = None


@dataclass
class Conversation:
    """Full state of one active conversation."""

    # Identity
    conversation_id: str
    merchant_id: str
    customer_id: Optional[str] = None
    trigger_id: Optional[str] = None

    # Turn tracking
    messages: List[Message] = field(default_factory=list)
    turn_number: int = 0

    # State machine
    state: ConversationState = ConversationState.NEW

    # Auto-reply detection
    auto_reply_streak: int = 0
    last_merchant_message: Optional[str] = None   # for exact-match detection

    # Repetition prevention
    last_sent_bodies: List[str] = field(default_factory=list)

    # Deduplication
    suppression_key: Optional[str] = None

    def add_message(self, role: str, body: str,
                    received_at: Optional[str] = None) -> None:
        """Append a new message and advance the turn counter."""
        self.turn_number += 1
        self.messages.append(
            Message(role=role, body=body,
                    turn_number=self.turn_number,
                    received_at=received_at)
        )

    def record_sent(self, body: str) -> None:
        """Record a body the bot sent (for repetition detection)."""
        self.last_sent_bodies.append(body)
        # Keep only the last 10 for memory efficiency
        if len(self.last_sent_bodies) > 10:
            self.last_sent_bodies = self.last_sent_bodies[-10:]

    def is_active(self) -> bool:
        """True when the conversation can still receive new messages."""
        return self.state not in (
            ConversationState.ENDED,
            ConversationState.NOT_INTERESTED,
        )

    def is_ended(self) -> bool:
        return self.state in (
            ConversationState.ENDED,
            ConversationState.NOT_INTERESTED,
        )


class ConversationStore:
    """
    Thread-safe in-memory store for Conversation objects.

    Usage:
        store = ConversationStore()
        conv = store.create("conv_001", "m_001", trigger_id="trg_abc")
        store.get("conv_001")           → Conversation | None
        store.update(conv)              → None  (writes back)
        store.all_active()              → list[Conversation]
        store.is_suppressed(key)        → bool
        store.suppress(key, conv_id)    → None
    """

    def __init__(self) -> None:
        self._conversations: Dict[str, Conversation] = {}
        # suppression_key → conversation_id that "owns" this key
        self._suppressed: Dict[str, str] = {}
        self._lock = threading.Lock()

    # ------------------------------------------------------------------
    # CRUD
    # ------------------------------------------------------------------

    def create(
        self,
        conversation_id: str,
        merchant_id: str,
        customer_id: Optional[str] = None,
        trigger_id: Optional[str] = None,
        suppression_key: Optional[str] = None,
    ) -> Conversation:
        """Create and register a new conversation. Raises if ID already exists."""
        with self._lock:
            if conversation_id in self._conversations:
                raise ValueError(
                    f"Conversation '{conversation_id}' already exists. "
                    "Use a unique ID for each new conversation."
                )
            conv = Conversation(
                conversation_id=conversation_id,
                merchant_id=merchant_id,
                customer_id=customer_id,
                trigger_id=trigger_id,
                suppression_key=suppression_key,
            )
            self._conversations[conversation_id] = conv
            if suppression_key:
                self._suppressed[suppression_key] = conversation_id
            return conv

    def get(self, conversation_id: str) -> Optional[Conversation]:
        """Look up a conversation by ID."""
        with self._lock:
            return self._conversations.get(conversation_id)

    def update(self, conv: Conversation) -> None:
        """Persist a modified conversation object back to the store."""
        with self._lock:
            self._conversations[conv.conversation_id] = conv

    def delete(self, conversation_id: str) -> bool:
        """Remove a conversation (used on teardown). Returns True if it existed."""
        with self._lock:
            conv = self._conversations.pop(conversation_id, None)
            if conv and conv.suppression_key:
                self._suppressed.pop(conv.suppression_key, None)
            return conv is not None

    # ------------------------------------------------------------------
    # Query helpers
    # ------------------------------------------------------------------

    def all_active(self) -> List[Conversation]:
        """Return all conversations that are still active."""
        with self._lock:
            return [c for c in self._conversations.values() if c.is_active()]

    def all_for_merchant(self, merchant_id: str) -> List[Conversation]:
        """Return all conversations (any state) for a given merchant."""
        with self._lock:
            return [
                c for c in self._conversations.values()
                if c.merchant_id == merchant_id
            ]

    def count(self) -> int:
        with self._lock:
            return len(self._conversations)

    # ------------------------------------------------------------------
    # Suppression / dedup
    # ------------------------------------------------------------------

    def is_suppressed(self, suppression_key: str) -> bool:
        """True if a conversation with this suppression_key already exists."""
        with self._lock:
            return suppression_key in self._suppressed

    def suppress(self, suppression_key: str, conversation_id: str) -> None:
        """Register a suppression key (called when the bot initiates a new convo)."""
        with self._lock:
            self._suppressed[suppression_key] = conversation_id

    def release_suppression(self, suppression_key: str) -> None:
        """Remove a suppression key (e.g., after context version bump allows re-send)."""
        with self._lock:
            self._suppressed.pop(suppression_key, None)

    def clear(self) -> None:
        """Wipe everything (for teardown / test isolation)."""
        with self._lock:
            self._conversations.clear()
            self._suppressed.clear()
